# --- General Settings ---

# Change the prefix from Ctrl+b to Alt+a / Alt is same as M for Meta
unbind C-b
set -g prefix M-a
bind M-a send-prefix

# Enable mouse support (click to select panes, resize, and scroll)
set -g mouse on

# Split panes using h and v
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# --- Visuals ---

# Improve colors
set -g default-terminal "screen-256color"
# Enable border status string
set -g pane-border-status top
set -g pane-border-format " [ #P: #{pane_title} ] "
# Press Prefix + R to bring up a prompt to rename the current pane
# Bind 'r' to a new keymap, then 'n' to the rename command
bind r switch-client -T rename-map
bind -T rename-map n command-prompt -I "#T" "select-pane -T '%%'"
